blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/CernalGhost/SquirrelLove/discussions
    about: Ask questions or share ideas that are not bug reports or feature requests
